---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tap.tanzu.vmware.com/pipeline: java
    tap.tanzu.vmware.com/scanpolicy: lax
  labels:
    apps.tanzu.vmware.com/tap-ns: ""
  name: java-dev
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tap.tanzu.vmware.com/pipeline: java
    tap.tanzu.vmware.com/scanpolicy: strict
  labels:
    apps.tanzu.vmware.com/tap-ns: ""
  name: java-test
