apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: my-app
  namespace: dev
spec:
  serviceAccountName: default-ns-sa
  syncPeriod: 1m
  fetch:
  - git:
      url: https://github.com/atmandhol/tap-nsp-gitops.git
      ref: origin/main
      subPath: random/contents
  template:
  - ytt:
      valuesFrom:
      - configMapRef:
          name: app-config
  deploy:
    - kapp:
        rawOptions: ["--dangerous-allow-empty-list-of-resources=true"]
