#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ def in_list(key, list):
#@  return hasattr(data.values.tap_values, key) and (data.values.tap_values[key] in list)
#@ end
#@ if/end in_list('supply_chain', ['testing_scanning']) and in_list('profile', ['full', 'build']) and hasattr(data.values, 'scanners') and "snyk" in data.values.scanners:
---
apiVersion: v1
kind: Secret
metadata:
  name: snyk-token-secret
data:
  snyk_token: #@ base64.encode(data.values.imported.scanners.snyk_token)