#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:yaml", "yaml")
#@ def in_list(key, list):
#@  return hasattr(data.values.tap_values, key) and (data.values.tap_values[key] in list)
#@ end
#@ def get_snyk_values():
#@   snyk_values = {}
#@   snyk_values["namespace"] = data.values.name
#@   snyk_values["targetImagePullSecret"] = "registries-credentials"
#@   snyk_values["snyk"] = {"tokenSecret": {"name": "snyk-token-secret"}}
#@   snyk_values["metadataStore"] = {"url": ""}
#@   return snyk_values
#@ end
#@ if in_list('supply_chain', ['testing_scanning']) and in_list('profile', ['full', 'build']):
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: "snyk-scanner"
  namespace: tap-install
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
spec:
  packageRef:
    refName: snyk.scanning.apps.tanzu.vmware.com
    versionSelection:
      constraints: ">0.0.0"
      prereleases: {}
  serviceAccountName: tap-install-sa
  values:
  - secretRef:
      name: #@ "snyk-scanner-" + data.values.name
---
apiVersion: v1
kind: Secret
metadata:
  name: "snyk-scanner"
  namespace: tap-install
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
stringData:
  values.yml: #@ yaml.encode(get_snyk_values())
#@ end