#@ load("@ytt:data", "data")
#@ def in_list(key, list):
#@  return hasattr(data.values.tap_values, key) and (data.values.tap_values[key] in list)
#@ end
#@ if/end in_list('supply_chain', ['testing_scanning']) and in_list('profile', ['full', 'build']):
---
apiVersion: v1
kind: Secret
metadata:
  name: snyk-token-secret
data:
  snyk_token: #@ data.values.imported.scanners.snyk_api_token if hasattr(data.values, "imported") and hasattr(data.values.imported, "scanners") and hasattr(data.values.imported.scanners, "snyk_api_token") else ""