#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ def in_list(key, list):
#@  return hasattr(data.values.tap_values, key) and (data.values.tap_values[key] in list)
#@ end
#@ if/end in_list('supply_chain', ['testing_scanning']) and in_list('profile', ['full', 'build']):
---
apiVersion: v1
kind: Secret
metadata:
  name: cb-config
stringData:
  cbc_api_id: #@ base64.encode(data.values.imported.cb.api_id) if hasattr(data.values, "imported") and hasattr(data.values.imported, "cb") else ""
  cbc_api_key: #@ base64.encode(data.values.imported.cb.api_key) if hasattr(data.values, "imported") and hasattr(data.values.imported, "cb") else ""
  cbc_org_key: #@ base64.encode(data.values.imported.cb.org_key) if hasattr(data.values, "imported") and hasattr(data.values.imported, "cb") else ""
  cbc_saas_url: #@ base64.encode(data.values.imported.cb.saas_url) if hasattr(data.values, "imported") and hasattr(data.values.imported, "cb") else ""