#@ load("@ytt:data", "data")
#@ load("@scan:funcs.star", "in_list", "is_supply_chain", "is_profile", "get_scanner_for_ns")
#@ if/end is_supply_chain(['testing_scanning']) and is_profile(['full', 'build']) and in_list("snyk", get_scanner_for_ns()):
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: snyk-token-secret
spec:
  data:
  - secretKey: snyk_token
    remoteRef:
      key: snyk_token
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: google-secrets-manager
  target:
    name: snyk-token-secret