#@ load("@ytt:data", "data")
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: buildpack-build-workload-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: buildpack-build-workload-cluster-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: #@ data.values.name
