#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
#@ load("@ytt:base64", "base64")
#@ def generate_dockerconfigjson():
#@   dcj = {"auths": {}}
#@   up = {"username": data.values.imported.tanzusupplychain.ocistore.username, "password": data.values.imported.tanzusupplychain.ocistore.password}
#@   dcj["auths"][data.values.imported.tanzusupplychain.ocistore.server] = up
#@   return base64.encode(json.encode(dcj))
#@ end
---
apiVersion: v1
data:
  .dockerconfigjson: #@ generate_dockerconfigjson()
kind: Secret
metadata:
  name: oci-store-credentials
  annotations:
    tekton.dev/docker-0: #@ data.values.imported.tanzusupplychain.ocistore.server + "/" + data.values.imported.tanzusupplychain.ocistore.repository
type: kubernetes.io/dockerconfigjson
