---
tap_install:
  values:
    shared:
      ingress_domain: 127.0.0.1.nip.io
      ingress_issuer: ""
      kubernetes_distribution: ""
    namespace_provisioner:
      controller: false
      additional_sources:
      # All my scan setup
      - git:
          ref: origin/main
          subPath: namespace/scan
          url: https://github.com/atmandhol/tap-nsp-gitops.git
        path: _ytt_lib/scan-setup
      # Initial dir that has all the namespaces that needs to be managed by Namespace provisioner
      # and other bootstrapping items like registry-credentials, externalsecret to import the user-secrets, rabbitmq operators etc.
      gitops_install:
        ref: origin/main
        subPath: install
        url: https://github.com/atmandhol/tap-nsp-gitops.git
      # Import a yaml secret named user-secrets that is imported by ESO
      # as the external secret for that is part of gitops_install dir.
      # that yaml secret has all my other secrets like scanner tokens, git creds, dns stuff etc.
      # We import that yaml secret in Namespace provisioner so we can refer to values in there using data.values.imported key
      import_data_values_secrets:
        - name: user-secrets
          namespace: tap-install
          create_export: true
    ceip_policy_disclosed: true
    profile: full
    supply_chain: testing_scanning
    ootb_supply_chain_testing_scanning:
      gitops:
        ssh_secret: ""
    cnrs:
      domain_name: 127.0.0.1.nip.io
    contour:
      infrastructure_provider: vsphere
      envoy:
        service:
          type: LoadBalancer
    tap_gui:
      app_config:
        catalog:
          locations:
          - target: https://github.com/atmandhol/tap-blank-catalog/blob/main/catalog-info.yaml
            type: url
      ingressEnabled: "true"
      service_type: ClusterIP
    grype:
      targetImagePullSecret: registries-credentials
    metadata_store:
      ns_for_export_app_cert: '*'
      app_service_type: ClusterIP
      ingress_enabled: "true"
    excluded_packages:
    - learningcenter.tanzu.vmware.com
    - workshops.learningcenter.tanzu.vmware.com
    tap_telemetry:
      installed_for_vmware_internal_use: "true"
