---
tap_install:
  values:
    shared:
      ingress_domain: 127.0.0.1.nip.io
      ingress_issuer: ""
      kubernetes_distribution: ""
    ceip_policy_disclosed: true
    profile: full
    supply_chain: testing_scanning
    ootb_supply_chain_testing_scanning:
      gitops:
        repository_name: tap-gitops
        repository_owner: atmandhol
        server_address: https://github.com/
        ssh_secret: git
    cnrs:
      domain_name: 127.0.0.1.nip.io
    contour:
      infrastructure_provider: vsphere
      envoy:
        service:
          type: LoadBalancer
    tap_gui:
      app_config:
        catalog:
          locations:
          - target: https://github.com/atmandhol/tap-blank-catalog/blob/main/catalog-info.yaml
            type: url
      ingressEnabled: "true"
      service_type: ClusterIP
    grype:
      targetImagePullSecret: registries-credentials
    metadata_store:
      ns_for_export_app_cert: '*'
      app_service_type: ClusterIP
      ingress_enabled: "true"
    excluded_packages:
    - learningcenter.tanzu.vmware.com
    - workshops.learningcenter.tanzu.vmware.com
    tap_telemetry:
      installed_for_vmware_internal_use: "true"
    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/showcase
        subPath: install
        url: https://github.com/atmandhol/tap-nsp-gitops.git