#@ load("@ytt:data", "data")
#@ load("@scan:funcs.star", "is_profile")
#@ if/end is_profile(['full', 'iterate', 'run']):
---
apiVersion: v1
kind: LimitRange
metadata:
  name: namespace-resource-constraints
spec:
  limits:
  - default:
      cpu: #@ lambda: data.values.tap.default-cpu-limit if hasattr(data.values, "tap") and hasattr(data.values.tap, "default-cpu-limit") else "1000m"
      memory: #@ lambda: data.values.tap.default-mem-limit if hasattr(data.values, "tap") and hasattr(data.values.tap, "default-mem-limit") else "1Gi"
    defaultRequest:
      cpu: #@ lambda: data.values.tap.default-cpu-request if hasattr(data.values, "tap") and hasattr(data.values.tap, "default-cpu-request") else "100m"
      memory: #@ lambda: data.values.tap.default-mem-request if hasattr(data.values, "tap") and hasattr(data.values.tap, "default-mem-request") else "100Mi"
    type: Container
