#@data/values-schema
#@overlay/match-child-defaults missing_ok=True
---
tap_install:
  secrets:
    eso:
      aws:
        #! SecretStore config
        tap_install_secrets:
          roleARN: ""
      gcp:
        #! SecretStore config
        project: ""
        region: ""
        cluster: ""
        tap_install_secrets:
          serviceAccount: ""
      #! ESO remoteRefs, by Kubernetes Secret name, then data[].secretkey
      remote_refs:
        tap_sensitive_values:
          sensitive_tap_values_yaml:
            key: dev/tap/sensitive-values.yaml
