#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tap-install-secrets
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: eso/secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: tap-install-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: #@ data.values.tap_install.secrets.eso.aws.tap_install_secrets.roleARN
  name: tap-install-secrets
  namespace: tap-install
