---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: external-secrets-operator
  namespace: tap-install
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
spec:
  packageRef:
    refName: external-secrets.apps.tanzu.vmware.com
    versionSelection:
      constraints: ">0.0.0"
      prereleases: {}
  serviceAccountName: tap-install-sa
