#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
#@ load("@ytt:base64", "base64")
#@ def generate_dockerconfigjson():
#@   dcj = {"auths": {}}
#@   up = {"username": data.values.tap_values.shared.image_registry.username, "password": data.values.tap_values.shared.image_registry.password}
#@   dcj["auths"][data.values.tap_values.shared.image_registry.project_path.split("/")[0]] = up
#@   return base64.encode(json.encode(dcj))
#@ end
---
apiVersion: v1
data:
  .dockerconfigjson: #@ generate_dockerconfigjson()
kind: Secret
metadata:
  name: registry-credentials
  namespace: tap-install
type: kubernetes.io/dockerconfigjson
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: registry-credentials
  namespace: tap-install
spec:
  toNamespaces:
  - '*'