---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: user-secrets
  namespace: tap-install
spec:
  secretStoreRef:
    name: tap-install-secrets
    kind: SecretStore
  refreshInterval: "0m"
  data:
  - secretKey: user-secrets.yaml
    remoteRef:
      key: user-secrets