apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: desired-namespaces-sync
  namespace: tap-namespace-provisioning
spec:
  serviceAccountName: provisioner
  syncPeriod: 1m
  fetch:
  - git:
      url: https://github.com/atmandhol/tap-nsp-gitops.git
      ref: origin/main
      subPath: ns
      # Add this secretRef if you are talking to a private repo
      # secretRef:
      #   name: git-creds-carvel
  template:
  - ytt:
      valuesFrom:
            - secretRef:
                name: tap-values-config
  deploy:
    - kapp:
        rawOptions: ["--dangerous-allow-empty-list-of-resources=true", "--dangerous-override-ownership-of-existing-resources=true"]
