#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tanzu-sync-secrets
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-group: eso/secretstore
    kapp.k14s.io/change-rule.0: "upsert after upserting eso/install"
    kapp.k14s.io/change-rule.1: "delete before deleting eso/install"
spec:
  provider:
    #! aws:
    #!   service: SecretsManager
    #!   region: us-west-2
    #!   auth:
    #!     jwt:
    #!       serviceAccountRef:
    #!         name: tanzu-sync-secrets
    gcpsm:
      projectID: #@ data.values.secrets.eso.gcp.project
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: tanzu-sync-secrets
          clusterLocation: #@ data.values.secrets.eso.gcp.region
          clusterName: #@ data.values.secrets.eso.gcp.cluster
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    #! eks.amazonaws.com/role-arn: data.values.secrets.eso.aws.tanzu_sync_secrets.roleARN
    iam.gke.io/gcp-service-account: #@ data.values.secrets.eso.gcp.tanzu_sync_secrets.serviceAccount
  name: tanzu-sync-secrets
  namespace: tanzu-sync
